routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');

});


Route::group(['prefix'=>'admin','middleware'=>['auth','admin']],function (){
    Route::get('/','HomeController@admin')->name('admin');

    Route::resource('school','SchoolController');
    Route::resource('grade','GradeController');
    Route::resource('subject','SubjectController');



 });




Route::group(['prefix'=>'school','middleware'=>['auth','school']],function (){
    Route::get('/','HomeController@school')->name('school');


});

Route::group(['prefix'=>'parent','middleware'=>['auth','parent']],function (){
    Route::get('/','HomeController@parent')->name('parent');
 });


Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/dashboard.blade.php
@extends('layouts/admin')
@section('title')
    Admin Dashboard |School.com
    @endsection
 @section('content')
     <div class="row">
         <div class="col-lg-3 col-md-6">
             <div class="ibox bg-success color-white widget-stat">
                 <div class="ibox-body">
                     <h2 class="m-b-5 font-strong">201</h2>
                     <div class="m-b-5">NEW ORDERS</div><i class="ti-shopping-cart widget-stat-icon"></i>
                     <div><i class="fa fa-level-up m-r-5"></i><small>25% higher</small></div>
                 </div>
             </div>
         </div>
         <div class="col-lg-3 col-md-6">
             <div class="ibox bg-info color-white widget-stat">
                 <div class="ibox-body">
                     <h2 class="m-b-5 font-strong">1250</h2>
                     <div class="m-b-5">UNIQUE VIEWS</div><i class="ti-bar-chart widget-stat-icon"></i>
                     <div><i class="fa fa-level-up m-r-5"></i><small>17% higher</small></div>
                 </div>
             </div>
         </div>
         <div class="col-lg-3 col-md-6">
             <div class="ibox bg-warning color-white widget-stat">
                 <div class="ibox-body">
                     <h2 class="m-b-5 font-strong">$1570</h2>
                     <div class="m-b-5">TOTAL INCOME</div><i class="fa fa-money widget-stat-icon"></i>
                     <div><i class="fa fa-level-up m-r-5"></i><small>22% higher</small></div>
                 </div>
             </div>
         </div>
         <div class="col-lg-3 col-md-6">
             <div class="ibox bg-danger color-white widget-stat">
                 <div class="ibox-body">
                     <h2 class="m-b-5 font-strong">108</h2>
                     <div class="m-b-5">NEW USERS</div><i class="ti-user widget-stat-icon"></i>
                     <div><i class="fa fa-level-down m-r-5"></i><small>-12% Lower</small></div>
                 </div>
             </div>
         </div>
     </div>

     <div class="row">
         <div class="col-lg-12">
             <div class="ibox">
                 <div class="ibox-head">
                     <div class="ibox-title">Latest Orders</div>
                     <div class="ibox-tools">

                     </div>
                 </div>
                 <div class="ibox-body">
                     <table class="table table-striped table-hover">
                         <thead>
                         <tr>
                             <th>Order ID</th>
                             <th>Customer</th>
                             <th>Amount</th>
                             <th>Status</th>
                             <th width="91px">Date</th>
                         </tr>
                         </thead>
                         <tbody>
                         <tr>
                             <td>
                                 <a href="invoice.html">AT2584</a>
                             </td>
                             <td>@Jack</td>
                             <td>$564.00</td>
                             <td>
                                 <span class="badge badge-success">Shipped</span>
                             </td>
                             <td>10/07/2017</td>
                         </tr>
                         <tr>
                             <td>
                                 <a href="invoice.html">AT2575</a>
                             </td>
                             <td>@Amalia</td>
                             <td>$220.60</td>
                             <td>
                                 <span class="badge badge-success">Shipped</span>
                             </td>
                             <td>10/07/2017</td>
                         </tr>
                         <tr>
                             <td>
                                 <a href="invoice.html">AT1204</a>
                             </td>
                             <td>@Emma</td>
                             <td>$760.00</td>
                             <td>
                                 <span class="badge badge-default">Pending</span>
                             </td>
                             <td>10/07/2017</td>
                         </tr>
                         <tr>
                             <td>
                                 <a href="invoice.html">AT7578</a>
                             </td>
                             <td>@James</td>
                             <td>$87.60</td>
                             <td>
                                 <span class="badge badge-warning">Expired</span>
                             </td>
                             <td>10/07/2017</td>
                         </tr>
                         <tr>
                             <td>
                                 <a href="invoice.html">AT0158</a>
                             </td>
                             <td>@Ava</td>
                             <td>$430.50</td>
                             <td>
                                 <span class="badge badge-default">Pending</span>
                             </td>
                             <td>10/07/2017</td>
                         </tr>
                         <tr>
                             <td>
                                 <a href="invoice.html">AT0127</a>
                             </td>
                             <td>@Noah</td>
                             <td>$64.00</td>
                             <td>
                                 <span class="badge badge-success">Shipped</span>
                             </td>
                             <td>10/07/2017</td>
                         </tr>
                         </tbody>
                     </table>
                 </div>
             </div>
         </div>
     </div>
@endsection

resources/views/admin/grade-form.blade.php
@extends('layouts/admin')
@section('title','Class' .(isset($data) ? '  Update':  'Add'). ' |School.com')

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-name">Class {{isset($data) ? 'Update' : 'Add'}} Form</div>
                    <div class="ibox-tools">

                    </div>
                </div>
                <div class="ibox-body">

                    @if(isset($data))
                        {{ Form:: open(['url'=>route('grade.update',$data->id),'class'=>'form','files'=>true])}}
                        @method('patch')
                    @else
                        {{ Form:: open(['url'=>route('grade.store'),'class'=>'form','files'=>true])}}

                    @endif


                    <div class="form-group row">
                        {{Form::label('gradename','Grade Name:',['class'=>'col-sm-3'])}}
                        <div class="col-sm-9">
                            {{Form::text('gradename',@$data->gradename,['class'=>' form-control form-control-sm','id'=>'gradename','require'=>true,'placeholder'=>'Enterschool Garde Name... '])}}
                            @error('gradename')
                            <span class="alert-danger"></span>
                            @enderror
                        </div>
                    </div>



                    <div class="form-group row">
                        {{Form::label('status','Status:',['class'=>'col-sm-3'])}}
                        <div class="col-sm-9">
                            {{Form::select('status',['active'=>'Active','inactive'=>'In-Active'],@$data->status,['class'=>'form-control form-control-sm','id'=>'status','required'=>true])}}
                            @error('status')
                            <span class="alert-danger">{{$message}}}</span>
                            @enderror
                        </div>
                    </div>




                    <div class="form-group row">
                        {{Form::label('','',['class'=>'col-sm-3'])}}
                        <div class="col-sm-9">
                            {{Form::button('<i class="fa fa-trash"></i> Reset',['class' => 'btm btn-danger btn-sm','type'=>'reset'])}}
                            {{Form::button('<i class="fa fa-paper-plane"></i> Submit',['class'=>'btm btn-success btn-sm','type'=>'submit'])}}

                        </div>
                    </div>

                    {{ Form:: close() }}
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/grade.blade.php
@extends('layouts/admin')
@section('title')
    Class List Page |School.com
@endsection
@section('content')





    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">Class List</div>
                    <div class="ibox-tools">

                    </div>
                </div>
                <div class="ibox-body">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>Class Name</th>
                            <th>Status</th>
                            <th>Added By</th>
                            <th width="91px">Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        @if($data)

                            @foreach($data as $key=>$info)
                                <tr>
                                    <td>{{$info->gradename}}</td>




                                    <td>
                                        <span class="badge badge-{{($info->status == 'active') ? 'success':'danger'}}">
                                            {{ucfirst($info->status =='active')?'Active':'In-Active' }}
                                        </span>
                                    </td>
                                    <td>{{$info->created_by['name']}}</td>
                                    <td>
                                        <a href="{{route('grade.edit',$info->id)}}" class="btn btn-success flote-left btn-sm btn-rounded" >
                                            <i class="fa fa-edit"></i>

                                        </a>

                                        {{Form::open(['url'=>route('grade.destroy',$info->id),'class'=>'form', "onsubmit"=>"return confirm('are you sure you want to delete?')"]) }}
                                        @csrf
                                        @method('delete ')
                                        <button type="submit" class="btn btn-danger flote-right btn-sm btn-rounded " style="margin-top:5px; " >
                                            <i class="fa fa-trash"></i>
                                        </button>
                                        {{Form::close()}}
                                    </td>
                                </tr>
                            @endforeach
                        @endif


                        </tbody>
                    </table>

                    {{$data->links()}}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')

    <script >
        $(document).ready(function(){
            $('.table').DataTable();
        });
    </script>
@endsection

resources/views/admin/school-form.blade.php
@extends('layouts/admin')
@section('title','School' .(isset($data) ? '  Update':  'Add'). ' |School.com')

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-name">School {{isset($data) ? 'Update' : 'Add'}} Form</div>
                    <div class="ibox-tools">

                    </div>
                </div>
                <div class="ibox-body">

                    @if(isset($data))
                        {{ Form:: open(['url'=>route('school.update',$data->id),'class'=>'form','files'=>true])}}
                        @method('patch')
                    @else
                        {{ Form:: open(['url'=>route('school.store'),'class'=>'form','files'=>true])}}

                    @endif


                    <div class="form-group row">
                        {{Form::label('name','Name:',['class'=>'col-sm-3'])}}
                        <div class="col-sm-9">
                            {{Form::text('name',@$data->name,['class'=>' form-control form-control-sm','id'=>'name','require'=>true,'placeholder'=>'Enterschool Schoo Name... '])}}
                            @error('name')
                            <span class="alert-danger"></span>
                            @enderror
                        </div>
                    </div>

                        <div class="form-group row">
                            {{Form::label('address','Address:',['class'=>'col-sm-3'])}}
                            <div class="col-sm-9">
                                {{Form::text('address',@$data->address,['class'=>' form-control form-control-sm','id'=>'address','require'=>true,'placeholder'=>'Enter School Address... '])}}
                                @error('address')
                                <span class="alert-danger">{{$message}}}</span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row">
                            {{Form::label('telephone','Telephone:',['class'=>'col-sm-3'])}}
                            <div class="col-sm-9">
                                {{Form::text('telephone',@$data->telephone,['class'=>' form-control form-control-sm','id'=>'telephone','require'=>true,'placeholder'=>'Enter school Telephone... '])}}
                                @error('telephone')
                                <span class="alert-danger">{{$message}}}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            {{Form::label('email','Email:',['class'=>'col-sm-3'])}}
                            <div class="col-sm-9">
                                {{Form::text('email',@$data->email,['class'=>' form-control form-control-sm',(isset($data)?'disabled':true),'id'=>'email','require'=>false,])}}
                                @error('email')
                                <span class="alert-danger">{{$message}}}</span>
                                @enderror
                            </div>
                        </div>



                    <div class="form-group row">
                        {{Form::label('status','Status:',['class'=>'col-sm-3'])}}
                        <div class="col-sm-9">
                            {{Form::select('status',['active'=>'Published','inactive'=>'Un-Published'],@$data->status,['class'=>'form-control form-control-sm','id'=>'status','required'=>true])}}
                            @error('status')
                            <span class="alert-danger">{{$message}}}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        {{Form::label('image','School logo:',['class'=>'col-sm-3'])}}
                        <div class="col-sm-4">
                            {{Form::file('image',['id'=>'image','required'=>(isset($data) ? false : true),'accept'=>'image/&'])}}
                            @error('image')
                            <span class="alert-danger">{{$message}}}</span>
                            @enderror
                        </div>
                        @if(isset($data))
                            <div class="col-sm-4">
                                <img src="{{asset('uploads/school/Thumb-'.$data->image)}}" alt="{{$data->name}}" class="img img-fluid img-thumbnail">
                            </div>
                        @endif
                    </div>

                    <div class="form-group row">
                        {{Form::label('','',['class'=>'col-sm-3'])}}
                        <div class="col-sm-9">
                            {{Form::button('<i class="fa fa-trash"></i> Reset',['class'=>'btm btn-danger btn-sm','type'=>'reset'])}}
                            {{Form::button('<i class="fa fa-paper-plane"></i> Submit',['class'=>'btm btn-success btn-sm','type'=>'submit'])}}

                        </div>
                    </div>

                    {{ Form:: close() }}
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/school.blade.php
@extends('layouts/admin')
@section('title')
    School List Page |School.com
@endsection

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">School List</div>
                    <div class="ibox-tools">

                    </div>
                </div>
                <div class="ibox-body">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>School Name</th>
                            <th>Address</th>

                            <th>Telephone</th>
                            <th>Email</th>

                            <th>Status</th>
                            <th>Added By</th>
                            <th width="91px">Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        @if($data)
                            @foreach($data as $key=>$info)

                                <tr >
                                    <td class="detail" data-id="{{$info->id}}">{{$info->name}}</td>
                                    <td>{{$info->address}}</td>
                                   {{-- <td>{{$info->location}}</td>--}}
                                    <td>{{$info->telephone}}</td>
                                    <td>{{$info->email}}</td>



                                {{--    <td>

                                       @if($info->image != null)
                                            @if(file_exists(public_path().'/uploads/school/Thumb-'.$info->image))
                                                <img src="{{asset('uploads/school/Thumb-'.$info->image)}}" style="max-width:150px" alt="{{$info->title}}" class="img-thumbnail img-fluid">
                                            @elseif(file_exists(public_path().'/uploads/school/'.$info->image))
                                                <img src="{{asset('uploads/school/'.$info->image)}}"style="max-width: 150px" alt="{{$info->title}}" class="img-thumbnail img-fluid">
                                            @else
                                                No image found.
                                            @endif
                                        @else
                                            No Image uploaded
                                        @endif

                                    </td>--}}


                                    <td>
                                        <span class="badge badge-{{($info->status == 'active') ? 'success':'danger'}}">
                                            {{ucfirst($info->status =='active')?'Published':'Un-published' }}
                                        </span>
                                    </td>
                                    <td>{{$info->created_by['name']}}</td>
                                    <td>
                                        <a href="{{route('school.edit',$info->id)}}" class="btn btn-success flote-left btn-sm btn-rounded" >
                                            <i class="fa fa-edit"></i>

                                        </a>





                                        {{Form::open(['url'=>route('school.destroy',$info->id),'class'=>'form','onsubmit'=>'return confirm("Are you sure you want to delete?")']) }}
                                        @method('delete ')
                                        <button type="submit" class="btn btn-danger flote-right btn-sm btn-rounded " style="margin-top:5px; " >
                                            <i class="fa fa-trash"></i>
                                        </button>
                                        {{Form::close()}}


                                    </td>
                                </tr>
                            @endforeach
                        @endif


                        </tbody>
                    </table>

                    {{$data->links()}}
                </div>
            </div>
        </div>
    </div>
    @endsection
@section('scripts')

    <script >
        $(document).ready(function(){
            $('.table').DataTable({
               /* "order": ['id', 'asc']*/
            });
        });
    </script>
    <script >
        $('.detail').on('click',function () {
         document.location.href = `${document.location.href}/${$(this).data('id')}`;
        })
    </script>
@endsection

resources/views/admin/subject-form.blade.php
@extends('layouts/admin')
@section('title','Subject' .(isset($data) ? '  Update':  'Add'). ' |Subject.com')

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-name">Subject {{isset($data) ? 'Update' : 'Add'}} Form</div>
                    <div class="ibox-tools">

                    </div>
                </div>
                <div class="ibox-body">

                    @if(isset($data))
                        {{ Form:: open(['url'=>route('subject.update',$data->id),'class'=>'form','files'=>true])}}
                        @method('patch')
                    @else
                        {{ Form:: open(['url'=>route('subject.store'),'class'=>'form','files'=>true])}}

                    @endif


                    <div class="form-group row">
                        {{Form::label('title','Subject Name:',['class'=>'col-sm-3'])}}
                        <div class="col-sm-9">
                            {{Form::text('title',@$data->title,['class'=>' form-control form-control-sm','id'=>'title','require'=>true,'placeholder'=>'Enter title Name... '])}}
                            @error('title')
                            <span class="alert-danger"></span>
                            @enderror
                        </div>
                    </div>


                        <div class="form-group row">
                            {{Form::label('description','Subject Description:',['class'=>'col-sm-3'])}}
                            <div class="col-sm-9">
                                {{Form::textarea('description',@$data->description,['class'=>' form-control form-control-sm','id'=>'description','require'=>true,])}}
                                @error('description')
                                <span class="alert-danger"></span>
                                @enderror
                            </div>
                        </div>



                        <div class="form-group row">
                        {{Form::label('status','Status:',['class'=>'col-sm-3'])}}
                        <div class="col-sm-9">
                            {{Form::select('status',['active'=>'Published','inactive'=>'Un-Published'],@$data->status,['class'=>'form-control form-control-sm','id'=>'status','required'=>true])}}
                            @error('status')
                            <span class="alert-danger">{{$message}}}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        {{Form::label('file','File:',['class'=>'col-sm-3'])}}
                        <div class="col-sm-4">
                            {{Form::file('file',['id'=>'file','required'=>(isset($data) ? false : true),'accept'=>'file'])}}
                            @error('file')
                            <span class="alert-danger">{{$message}}}</span>
                            @enderror
                        </div>

                    </div>

                    <div class="form-group row">
                        {{Form::label('','',['class'=>'col-sm-3'])}}
                        <div class="col-sm-9">
                            {{Form::button('<i class="fa fa-trash"></i> Reset',['class'=>'btm btn-danger btn-sm','type'=>'reset'])}}
                            {{Form::button('<i class="fa fa-paper-plane"></i> Submit',['class'=>'btm btn-success btn-sm','type'=>'submit'])}}

                        </div>
                    </div>

                    {{ Form:: close() }}
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/subject.blade.php
@extends('layouts/admin')
@section('title')
    Subject List Page |School.com
@endsection

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">Subject List</div>
                    <div class="ibox-tools">

                    </div>
                </div>
                <div class="ibox-body">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>Subject Name</th>
                            <th>Description</th>
                             <th>File</th>
                            <th>Status</th>
                            <th>Added By</th>
                            <th width="91px">Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        @if($data)
                            @foreach($data as $key=>$info)

                                <tr >
                                    <td>{{$info->title}}</td>

                                    <td>{{$info->description}}</td>
                                        <td>
                                           @if($info->file != null)
                                                @if(file_exists(public_path().'/uploads/files/subject/'.$info->file))
                                                    {{ $info->file }}
                                                @else
                                                    No file found.
                                                @endif
                                            @else
                                                No File uploaded
                                            @endif

                                        </td>


                                    <td>
                                        <span class="badge badge-{{($info->status == 'active') ? 'success':'danger'}}">
                                            {{ucfirst($info->status =='active')?'Active':'Inactive' }}
                                        </span>
                                    </td>
                                    <td>{{$info->created_by['name']}}</td>
                                    <td>
                                        <a href="{{route('subject.edit',$info->id)}}" class="btn btn-success flote-left btn-sm btn-rounded" >
                                            <i class="fa fa-edit"></i>

                                        </a>





                                        {{Form::open(['url'=>route('subject.destroy',$info->id),'class'=>'form','onsubmit'=>'return confirm("Are you sure you want to delete?")']) }}
                                        @method('delete ')
                                        <button type="submit" class="btn btn-danger flote-right btn-sm btn-rounded " style="margin-top:5px; " >
                                            <i class="fa fa-trash"></i>
                                        </button>
                                        {{Form::close()}}


                                    </td>
                                </tr>
                            @endforeach
                        @endif


                        </tbody>
                    </table>

                    {{$data->links()}}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')

    <script >
        $(document).ready(function(){
            $('.table').DataTable({
                /* "order": ['id', 'asc']*/
            });
        });
    </script>
    <script >
        $('.detail').on('click',function () {
            document.location.href = `${document.location.href}/${$(this).data('id')}`;
        })
    </script>
@endsection