routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');

});


Route::group(['prefix'=>'admin','middleware'=>['auth','admin']],function (){
    Route::get('/','HomeController@admin')->name('admin');

    Route::resource('school','SchoolController');
    Route::resource('grade','GradeController');
    Route::resource('subject','SubjectController');



 });




Route::group(['prefix'=>'school','middleware'=>['auth','school']],function (){
    Route::get('/','HomeController@school')->name('school');


});

Route::group(['prefix'=>'parent','middleware'=>['auth','parent']],function (){
    Route::get('/','HomeController@parent')->name('parent');
 });


Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/section/copy.blade.php
<footer class="page-footer">
    <div class="font-13">2018 © <b>AdminCAST</b> - All rights reserved.</div>
    <a class="px-4" href="http://themeforest.net/item/adminca-responsive-bootstrap-4-3-angular-4-admin-dashboard-template/20912589" target="_blank">BUY PREMIUM</a>
    <div class="to-top"><i class="fa fa-angle-double-up"></i></div>
</footer>

resources/views/admin/section/footer.blade.php
</div>

<!-- BEGIN PAGA BACKDROPS-->
<div class="sidenav-backdrop backdrop"></div>
<div class="preloader-backdrop">
    <div class="page-preloader">Loading</div>
</div>
<!-- END PAGA BACKDROPS-->
<script src="{{asset('js/manifest.js')}}"></script>
<script src="{{asset('js/vendor.js')}}"></script>
<script src="{{asset('js/admin.js')}}"></script>

@yield('scripts')

</body>

</html>

resources/views/admin/section/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <title>@yield('title')</title>



    <link href="{{asset('css/admin.css')}}" rel="stylesheet" />

   @yield('styles')
</head>

<body class="fixed-navbar">
<div class="page-wrapper">

resources/views/admin/section/notify.blade.php
@if(session('success'))
    <p class="alert alert-success">{{session('success')}}</p>
@endif

@if(session('error'))
    <p class="alert alert-danger">{{session('error')}}</p>
@endif

resources/views/admin/section/sidebar.blade.php
<!-- START SIDEBAR-->
<nav class="page-sidebar" id="sidebar">
    <div id="sidebar-collapse">
        <div class="admin-block d-flex">
            <div>
                <i class="fa fa-user fa-2x" style="color: #ffffff"></i>
            </div>
            <div class="admin-info">
                <div class="font-strong">{{auth()->user()->name}}</div><small>{{ucfirst(auth()->user()->role)}}</small></div>
        </div>
        <ul class="side-menu metismenu">
            <li>
                <a class="active" href="{{route('home')}}"><i class="sidebar-item-icon fa fa-th-large"></i>
                    <span class="nav-label">Dashboard</span>
                </a>
            </li>
            <li class="heading">FEATURES</li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-school"></i>
                    <span class="nav-label">School Detail</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{route('school.create')}}">Add School </a>
                    </li>
                    <li>
                        <a href="{{route('school.index')}}">List School </a>
                    </li>



                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fas fa-person-booth"></i>
                    <span class="nav-label">
                       Class
                    </span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{route('grade.create')}}">Add Class</a>
                    </li>
                    <li>
                        <a href="{{route('grade.index')}}">List Class</a>
                    </li>



                </ul>
            </li>

            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-book-reader"></i>
                    <span class="nav-label">Subject</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{route('subject.create')}}">Subject Add</a>
                    </li>

                    <li>
                        <a href="{{route('subject.index')}}">Subject List</a>
                    </li>
--}}

                </ul>
            </li>


        </ul>
    </div>
</nav>
<!-- END SIDEBAR-->

resources/views/admin/section/top-nav.blade.php
<!-- START HEADER-->
<header class="header">
    <div class="page-brand">
        <a class="link" href="{{route('home')}}">
                    <span class="brand">Admin &nbsp;
                        <span class="brand-tip">School</span>
                    </span>
            <span class="brand-mini">AS</span>
        </a>
    </div>
    <div class="flexbox flex-1">
        <!-- START TOP-LEFT TOOLBAR-->
        <ul class="nav navbar-toolbar">
            <li>
                <a class="nav-link sidebar-toggler js-sidebar-toggler"><i class="ti-menu"></i></a>
            </li>

        </ul>
        <!-- END TOP-LEFT TOOLBAR-->
        <!-- START TOP-RIGHT TOOLBAR-->
        <ul class="nav navbar-toolbar">

            <li class="dropdown dropdown-user">
                <a class="nav-link dropdown-toggle link" data-toggle="dropdown">
                    <i class="fa fa-user fa-2x"></i>&nbsp;
                    <span></span>{{auth()->user()->name}}<i class="fa fa-angle-down m-l-5"></i></a>
                <ul class="dropdown-menu dropdown-menu-right">

                    <a class="dropdown-item" href="{{route('logout')}}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                        <i class="fa fa-power-off"></i>Logout
                    </a>
                    <form action="{{route('logout')}}" method="post" id="logout-form" class="d-none">
                        @csrf

                    </form>

                </ul>
            </li>
        </ul>
        <!-- END TOP-RIGHT TOOLBAR-->
    </div>
</header>
<!-- END HEADER-->